<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net7.0-windows</TargetFrameworks>
    <RootNamespace>RhinoChannelsPlugin</RootNamespace>
    <AssemblyName>RhinoChannelsPlugin</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU</Platforms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseSystemDrawing>true</UseSystemDrawing>
    <SupportedOSPlatform>windows</SupportedOSPlatform>
  </PropertyGroup>

  <PropertyGroup>
    <RhinoCommonPath Condition="'$(RhinoCommonPath)' == ''">C:\Program Files\Rhino 8\System\RhinoCommon.dll</RhinoCommonPath>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <Reference Include="RhinoCommon">
      <HintPath>$(RhinoCommonPath)</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Drawing" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0-windows'">
    <Reference Include="RhinoCommon">
      <HintPath>$(RhinoCommonPath)</HintPath>
      <Private>false</Private>
    </Reference>
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
  </ItemGroup>
</Project>
