extends:
  - component_defaults.yaml
  - component_defect_defaults.yaml
  - component_render.yaml

preparation:
  plugin_autoload:
    enabled: true
    path: "/path/to/rhino_channels_plugin/bin/Debug/net7.0-windows/RhinoChannelsPlugin.dll"
    required_commands:
      - CaptureRenderChannels
      - CaptureBaseColorMask
    strict: true
    verbose: true
  builtin_material_library:
    category: ["Architectural", "Metal"]
    subcategory1: ["Wall", "Corten"]
    subcategory2: ["Concrete", ""]
  materials:
    "component::slab": &component_concrete_materials [
      "Conc beige",
      "Conc brown dirty",
      "Conc stripes",
      "Conc yellow",
      "Concrete light",
      "Asphalt001_4K",
      "Asphalt01_2K",
      "Asphalt02_2K",
      "AsphaltPaint001_4K",
      "Asphalt_002",
      "asphalt_0001_color_4k",
      "asphalt_0002_color_4k",
      "asphalt_0003_color_4k",
      "asphalt_0004_color_4k",
      "ground_0011_color_2k",
      "tiles_0036_base_color_4k",
      "tiles_0042_color_2k",
      "concrete_0006_color_2k",
      "concrete_0013_color_2k",
      "concrete_0019_color_2k",
      "concrete_0022_color_2k",
      "concrete_0030_color_2k",
      "concrete_0031_color_2k",
      "concrete_0032_color_2k",
      "Concrete001_2K-JPG",
      "Concrete002_2K-JPG",
      "Concrete003_2K-PNG",
      "Concrete004_2K-PNG",
      "Concrete005_2K-PNG",
      "Concrete006_2K-PNG",
      "Concrete007_2K-PNG",
      "Concrete008_2K-PNG",
      "Concrete009_2K-PNG",
      "Concrete010_2K-PNG",
      "Concrete011_2K-PNG",
      "Concrete012_2K-PNG",
      "Concrete013_2K-PNG",
      "Concrete014_2K-PNG",
      "Concrete015_2K-PNG",
      "Concrete016_2K-PNG",
      "Concrete017_2K-PNG",
      "Concrete018_2K-PNG",
      "Concrete019_2K-PNG",
      "Concrete020_2K-PNG",
      "Concrete021_2K-PNG",
      "Concrete022_2K-PNG",
      "Concrete023_2K-PNG",
      "Concrete024_2K-PNG",
      "Concrete025_2K-PNG",
      "Concrete026_2K-PNG",
      "Concrete027_2K-PNG",
      "Concrete028_2K-PNG",
      "Concrete029_2K-PNG",
      "Concrete030_2K-PNG",
      "Concrete031_2K-PNG",
      "Concrete032_2K-PNG",
      "Concrete033_2K-PNG",
      "Concrete034_2K-PNG",
      "Concrete035_2K-PNG",
      "Concrete036_2K-PNG",
      "Concrete037_2K-PNG",
      "Concrete038_2K-PNG",
      "Concrete039_2K-PNG",
      "Concrete040_2K-PNG"
    ]
    "component::beam": *component_concrete_materials
    "component::parapet": *component_concrete_materials
    "component::bearing": [
      "Rubber001_2K-PNG",
      "Rubber002_2K-PNG",
      "Rubber003_2K-PNG",
      "Rubber004_2K-PNG",
      "plastic_0001_color_2k",
    ]
    "component::pier": *component_concrete_materials
    "defect::crack::CS1": &defect_crack_materials [
      "Conc dark gray",
      "Concrete dark",
      "Concrete rusty",
      "concrete_0006_color_2k",
      "concrete_0013_color_2k",
      "concrete_0019_color_2k",
      "concrete_0022_color_2k",
      "concrete_0030_color_2k",
      "concrete_0031_color_2k",
      "concrete_0032_color_2k",
      "Concrete001_2K-JPG",
      "Concrete002_2K-JPG",
      "Concrete003_2K-PNG",
      "Concrete004_2K-PNG",
      "Concrete005_2K-PNG",
      "Concrete006_2K-PNG",
      "Concrete007_2K-PNG",
      "Concrete008_2K-PNG",
      "Concrete009_2K-PNG",
      "Concrete010_2K-PNG",
      "Concrete011_2K-PNG",
      "Concrete012_2K-PNG",
      "Concrete013_2K-PNG",
      "Concrete014_2K-PNG",
      "Concrete015_2K-PNG",
      "Concrete016_2K-PNG",
      "Concrete017_2K-PNG",
      "Concrete018_2K-PNG",
      "Concrete019_2K-PNG",
      "Concrete020_2K-PNG",
      "Concrete021_2K-PNG",
      "Concrete022_2K-PNG",
      "Concrete023_2K-PNG",
      "Concrete024_2K-PNG",
      "Concrete025_2K-PNG",
      "Concrete026_2K-PNG",
      "Concrete027_2K-PNG",
      "Concrete028_2K-PNG",
      "Concrete029_2K-PNG",
      "Concrete030_2K-PNG",
      "Concrete031_2K-PNG",
      "Concrete032_2K-PNG",
      "Concrete033_2K-PNG",
      "Concrete034_2K-PNG",
      "Concrete035_2K-PNG",
      "Concrete036_2K-PNG",
      "Concrete037_2K-PNG",
      "Concrete038_2K-PNG",
      "Concrete039_2K-PNG",
      "Concrete040_2K-PNG"
    ]
    "defect::crack::CS2": *defect_crack_materials
    "defect::crack::CS3": *defect_crack_materials
    "defect::efflore::CS2": &defect_efflore_materials [
      "imperfection_0006_color_2k",
      "decals_0001_color_2k",
      "SurfaceImperfections011_2K-PNG",
      "GrungeWall01_2K",
      "GrungeWall02_2K",
      "GrungeWall03_2K",
      "Leaking001_2K-PNG",
      "Leaking002_2K-PNG",
      "Leaking003_2K-PNG",
      "Leaking004_2K-PNG",
      "Leaking005_2K-PNG",
      "Leaking006_2K-PNG",
      "Leaking007_2K-PNG",
      "Leaking008_2K-PNG",
      "Leaking009_2K-PNG"
    ]
    "defect::efflore::CS3": *defect_efflore_materials
    "defect::spalling::CS2": &defect_spalling_materials [
      "Conc dark gray",
      "Concrete dark",
      "Concrete rusty",
      "BrownRock06_2K",
      "BrownRock07_2K",
      "BrownRock08_2K",
      "BrownRock09_2K",
      "RedRock01_2K",
      "RedRock02_2K",
      "RedRock03_2K",
      "RedRock05_2K",
      "Rock13_2K",
      "RockFace01_2K",
      "Glass031_1K",
      "Gravel01_2K",
      "Gravel02_2K",
      "Gravel03_2K",
      "Gravel04_2K",
      "Gravel05_2K",
      "GravelWall01_2K",
      "GreyRock01_2K",
      "GreyRock02_2K",
      "GreyRock03_2K",
      "GreyRock04_2K",
      "GreyRock05_2K",
    ]
    "defect::spalling::CS3": *defect_spalling_materials
    "defect::exposed_rebar::CS2": &defect_rebar_materials [
      "CorrugatedSteel002_2K",
      "CorrugatedSteel004_2K",  
      "Corten darker",
      "Corten light",
      "Corten rusty",
      "Rust002_1K-JPG",
      "Rust002_2K",
      "Rust003_1K-JPG",
      "Rust003_2K",
      "Rust004_1K-JPG",
      "Rust004_2K",
      "Rust005_1K-JPG",
      "Rust005_2K",
      "Rust006_1K-JPG",
      "Rust006_2K",
      "Rust007_1K-JPG",
      "Rust008_1K-JPG",
      "Rust009_1K-JPG",
      "Rust010_1K-JPG",
      "SheetMetal001_2K",
      "SheetMetal002_2K",
      "SheetMetal004_2K",
      "Metal001_2K",
      "Metal002_2K",
      "Metal003_2K",
      "Metal004_2K",
      "Metal005_2K",
      "Metal006_2K",
      "Metal007_2K",
      "Metal008_2K",
      "Metal009_2K",
      "Metal010_2K",
      "Metal011_2K",
      "Metal012_2K",
      "Metal013_2K",
      "Metal014_2K",
      "Metal015_2K",
      "Metal016_2K",
      "Metal017_2K",
      "Metal018_2K",
      "Metal019_2K",
      "Metal020_1K-JPG",
      "Metal021_1K-JPG",
      "Metal022_1K-JPG",
      "Metal023_1K-JPG",
      "Metal024_1K-JPG",
      "Metal025_1K-JPG",
      "Metal026_1K-JPG",
      "Metal037_2K",
      "Metal038_2K",
      "Metal039_2K",
      "Metal040_2K",
      "Metal053B_1K-JPG",
      "Metal055B_1K-JPG",
      "Metal055C_1K-JPG",
      "MetalPlates010_2K-PNG",
      "MetalPlates011_2K-PNG",
      "MetalPlates012_2K-PNG",
      "MetalPlates013_2K-PNG"
    ]
    "defect::exposed_rebar::CS3": *defect_rebar_materials
  colors:
    "component::slab": Red
    "component::beam": Blue
    "component::parapet": Green
    "component::bearing": AliceBlue
    "component::pier": Brown
    "debug::normal": Cyan
    "debug::normal::component": Cyan
    "debug::normal::component::slab": Cyan
    "debug::normal::component::parapet": DeepSkyBlue
    "debug::normal::component::beam": SpringGreen
    "debug::normal::component::bearing": YellowGreen
    "debug::normal::component::pier": Orange
    "debug::normal::component::unknown": White
    "defect::crack::CS1": LightGreen
    "defect::crack::CS2": Yellow
    "defect::crack::CS3": OrangeRed
    "defect::efflore::CS2": LightSkyBlue
    "defect::efflore::CS3": DeepSkyBlue
    "defect::spalling::CS2": Gold
    "defect::spalling::CS3": DarkOrange
    "defect::exposed_rebar::CS2": Silver
    "defect::exposed_rebar::CS3": Gray
    "debug::reference_points": LawnGreen
    "debug::reference_points::crack": LawnGreen
    "debug::reference_points::efflore": Aqua
    "debug::reference_points::spalling": Orange
    "debug::seed": White
    "debug::seed::crack": Red
    "debug::seed::efflore": DeepSkyBlue
    "debug::seed::spalling": Gold
