preparation:
  materials:
    slab: "/Concrete Weathered 300cm"
    beam: "Concrete light"
    parapet: "/Concrete Weathered 300cm"
    bearing: "/Rubber Rough 001"
    pier: "/Concrete Simple G01 400cm"
  colors:
    slab: Red
    beam: Blue
    parapet: Green
    bearing: AliceBlue
    pier: Brown
    "defects::geometry::crack": OrangeRed
    "defects::geometry::efflore": LightYellow
    "defects::geometry::spall": Chocolate
    "defects::geometry::rebar": DarkSlateGray
    "defects::mask::crack": White
    "defects::mask::efflore": White
    "defects::mask::spall": White
    "defects::mask::rebar": White
    "defects::mask::exposed_rebar": White
    "defects::seeds": Magenta
