extends:
  - cube_defaults.yaml
  - cube_defect_defaults.yaml
  - cube_render.yaml

preparation:
  builtin_material_library:
    category: ["Architectural"]
    subcategory1: ["Wall"]
    subcategory2: ["Concrete"]
  texture_materials:
    texture_root_dir: "C:/path/to/your/texture_root"
    recursive: true
  materials:
    "geometry::cube": ["Concrete light"]
    "geometry::crack": ["Concrete rusty"]
  colors:
    "geometry::cube": Black
    "geometry::crack": Red
    "mask::CS1": Green
    "mask::CS2": Yellow
    "mask::CS3": Orange
